Documentation:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false

Style/AccessModifierIndentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
