Documentation:
  Enabled: false

SpaceBeforeFirstArg:
  Enabled: false

Style/AccessModifierIndentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/GuardClause:
  Enabled: false
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
