version: '2'
services:
  dev:
    build: .
    links:
      - db
    volumes:
      - .:/usr/src/app
    environment:
      - RAILS_ENV=development

  test:
    build: .
    volumes:
      - .:/usr/src/app
    links:
      - db
    environment:
      - RAILS_ENV=test
    command: [rspec]

  db:
    image: mysql:5.7.13
    env_file: .env
    volumes:
      - .container/mysql/data:/var/lib/mysql
      - .container/mysql:/usr/var/dump
    environment:
      - MYSQL_ROOT_PASSWORD=$DATABASE_PASS

  heroku:
    image: eleidan/heroku:jessie
    env_file: .env
    volumes:
      - .:/usr/src/app
      - .container/heroku:/root
