version: '2'
services:
  dev:
    build: .
    image: vacation_system
    links:
      - db
    volumes:
      - .:/home/phantom/app
      - .docker/.bash_history:/home/phantom/.bash_history
      - .docker/ruby/:/home/phantom/.rbenv/versions/2.2.3/
    environment:
      - SERVICE_NAME=vacation_system

  db:
    image: mysql:5.7.13
    env_file: .env
    volumes:
      - .docker/mysql/data:/var/lib/mysql
      - .docker/mysql:/usr/var/dump
    environment:
      - MYSQL_ROOT_PASSWORD=$DATABASE_PASS

  heroku:
    image: eleidan/heroku:jessie
    env_file: .env
    volumes:
      - .:/usr/src/app
      - .docker/heroku:/root

  bootstrap:
    image: vacation_system
    volumes:
      - .:/home/phantom/app
    command: [.docker/scripts/bootstrap]
